services:
  mysql:
    image: 'mariadb:lts'
    ports:
      - '${WP_ENV_MYSQL_PORT:-}:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - 'mysql:/var/lib/mysql'
  tests-mysql:
    image: 'mariadb:lts'
    ports:
      - '${WP_ENV_TESTS_MYSQL_PORT:-}:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tests-wordpress
    volumes:
      - 'mysql-test:/var/lib/mysql'
  wordpress:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: WordPress.Dockerfile
      args: &ref_0
        HOST_USERNAME: Alexander
        HOST_UID: '1000'
        HOST_GID: '1000'
    ports:
      - '${WP_ENV_PORT:-8888}:80'
    environment:
      APACHE_RUN_USER: '#1000'
      APACHE_RUN_GROUP: '#1000'
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WP_TESTS_DIR: /wordpress-phpunit
    volumes: &ref_1
      - >-
        C:\Users\Alexander\.wp-env\35a9bfb62ed544b565879a8c94ad86ae\WordPress:/var/www/html
      - >-
        C:\Users\Alexander\.wp-env\35a9bfb62ed544b565879a8c94ad86ae\WordPress-PHPUnit\tests\phpunit:/wordpress-phpunit
      - 'user-home:/home/Alexander'
      - >-
        D:\lib\database_minProjects\__test_taskes__\K_Telekom_OOO\wp\themes\app:/var/www/html/wp-content/themes/app
      - >-
        D:\lib\database_minProjects\__test_taskes__\K_Telekom_OOO\wp\plugins\advanced-custom-fields:/var/www/html/wp-content/plugins/advanced-custom-fields
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  tests-wordpress:
    depends_on:
      - tests-mysql
    build:
      context: .
      dockerfile: Tests-WordPress.Dockerfile
      args: *ref_0
    ports:
      - '${WP_ENV_TESTS_PORT:-8889}:80'
    environment:
      APACHE_RUN_USER: '#1000'
      APACHE_RUN_GROUP: '#1000'
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: tests-wordpress
      WORDPRESS_DB_HOST: tests-mysql
      WP_TESTS_DIR: /wordpress-phpunit
    volumes: &ref_2
      - >-
        C:\Users\Alexander\.wp-env\35a9bfb62ed544b565879a8c94ad86ae\tests-WordPress:/var/www/html
      - >-
        C:\Users\Alexander\.wp-env\35a9bfb62ed544b565879a8c94ad86ae\tests-WordPress-PHPUnit\tests\phpunit:/wordpress-phpunit
      - 'tests-user-home:/home/Alexander'
      - >-
        D:\lib\database_minProjects\__test_taskes__\K_Telekom_OOO\wp\themes\app:/var/www/html/wp-content/themes/app
      - >-
        D:\lib\database_minProjects\__test_taskes__\K_Telekom_OOO\wp\plugins\advanced-custom-fields:/var/www/html/wp-content/plugins/advanced-custom-fields
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  cli:
    depends_on:
      - wordpress
    build:
      context: .
      dockerfile: CLI.Dockerfile
      args: *ref_0
    volumes: *ref_1
    user: '1000:1000'
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WP_TESTS_DIR: /wordpress-phpunit
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  tests-cli:
    depends_on:
      - tests-wordpress
    build:
      context: .
      dockerfile: Tests-CLI.Dockerfile
      args: *ref_0
    volumes: *ref_2
    user: '1000:1000'
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: tests-wordpress
      WORDPRESS_DB_HOST: tests-mysql
      WP_TESTS_DIR: /wordpress-phpunit
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  phpmyadmin:
    image: phpmyadmin
    ports:
      - '${WP_ENV_PHPMYADMIN_PORT:-}:80'
    environment:
      PMA_PORT: 3306
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
  tests-phpmyadmin:
    image: phpmyadmin
    ports:
      - '${WP_ENV_TESTS_PHPMYADMIN_PORT:-}:80'
    environment:
      PMA_PORT: 3306
      PMA_HOST: tests-mysql
      PMA_USER: root
      PMA_PASSWORD: password
volumes:
  mysql: {}
  mysql-test: {}
  user-home: {}
  tests-user-home: {}
